[env:btt_kraken]
platform = ststm32
board = marlin_STM32H723ZG
framework = arduino
lib_ldf_mode = chain+
board_microros_distro = humble
board_microros_transport = serial
board_build.variants_dir = variants

build_flags = 
    ; 1. Enable USB CDC and trigger Marlin's PA11/PA12 pin mapping
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D PIO_FRAMEWORK_ARDUINO_USB_HIGHSPEED_FULLMODE
    -D USBCON
    
    ; 2. Satisfy the ldscript.ld memory variables for the 128KB Bootloader
    -Wl,--defsym=LD_FLASH_OFFSET=0x20000
    -Wl,--defsym=LD_MAX_SIZE=1024K
    
    ; 3. Tell the Cortex-M7 to shift its Interrupt Vector Table 
    -D USER_VECT_TAB_ADDRESS
    -D VECT_TAB_OFFSET=0x20000

lib_deps = 
    https://github.com/micro-ROS/micro_ros_platformio
    waspinator/AccelStepper@^1.64
    pfeerick/elapsedMillis@^1.0.6
    teemuatlut/TMCStepper@^0.7.3