[env:btt_kraken]
platform = ststm32
board = btt_kraken
framework = arduino
lib_ldf_mode = chain+
board_microros_distro = humble
board_microros_transport = serial

build_flags = 
    ; Enable USB CDC with the High-Speed-in-Full-Speed fix
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D PIO_FRAMEWORK_ARDUINO_USB_HIGHSPEED_FULLMODE
    -D USBCON
    -D USBD_PID=0x5740
    -D USBD_VID=0x0483
    -D USB_MANUFACTURER="\"BigTreeTech\""
    -D USB_PRODUCT="\"Kraken V1.0\""
    
    ; Define the Kraken's physical 25MHz crystal
    -D HSE_VALUE=25000000U

lib_deps = 
    https://github.com/micro-ROS/micro_ros_platformio
    waspinator/AccelStepper@^1.64
    pfeerick/elapsedMillis@^1.0.6
    teemuatlut/TMCStepper@^0.7.3